### ISSUE TITLE
Once instantiated one cannot appropriately update a client.config.access_token.... however as part of standard access_key rotation/refresh it needs to be changed.  

### ISSUE THREAD

**Issue by wxe** [square/square-python-sdk#19]
See - https://github.com/square/square-python-sdk/blob/master/square/configuration.py access_token is effectively a read-only property (of course you can update config._access_token but should not); this means that you have to instantiate a new client (or new config and ungracefully overwrite config in client) each time you  refresh your access token.  There should be a function to allow updates of access_token for a given client instantiation (or expose it as a normal property) so that after a refresh token, you can update the token.

**Comment by sseaman** [comment]
Thanks for reporting this.  We are investigating options to see what would be the best approach.

**Comment by sseaman** [comment]
Hey wxe.

The SDKs are immutable by design which means the client can not be mutated by the user after instantiation. The immutable design of the client makes it easier to reason about client usage code when developing in a multi-threaded or async-enabled environment.

If you want to set the access token, you must create a new client and pass in the access token. However, you do not need to create a new client with all the configuration from scratch because you can use any existing instance of a client to create a clone but with the new access token set in it. Cloning an existing client instance is enabled through the client builder.

Hope this helps!
